version: 2.1

orbs:
  docker: circleci/docker@2.1.2

jobs:
  build-base:
    machine:
      image: ubuntu-2004:current
    resource_class: <<parameters.resource>>
    parallelism: 5
    parameters:
      tag:
        type: string
      resource:
        type: string
    steps:
      - checkout
      - docker/install-docker
      - docker/check
      - docker/build:
          image: marcermarc/minecraft 
          tag: <<parameters.tag>>
          dockerfile: Dockerfiles/Base/<<parameters.tag>>.Dockerfile 
      - docker/push:
          image: marcermarc/minecraft
          tag: <<parameters.tag>>
  build-specific:
    machine:
      image: ubuntu-2004:current
    resource_class: <<parameters.resource>>
    parallelism: 5
    parameters:
      version:
        type: string
      mc_type:
        type: string
      baseimage:
        type: string
      resource:
        type: string
    steps:
      - checkout
      - docker/install-docker
      - docker/check
      - docker/build:
          image: marcermarc/minecraft
          tag: <<parameters.mc_type>>_<<parameters.version>>
          dockerfile: Dockerfiles/<<parameters.mc_type>>/<<parameters.baseimage>>.Dockerfile
          extra_build_args: '--build-arg VERSION=<<parameters.version>>'
      - docker/push:
          image: marcermarc/minecraft
          tag: <<parameters.mc_type>>_<<parameters.version>>

workflows:
  minecraft:
    jobs:
      - build-base:
          name: base-<<matrix.tag>>-<<matrix.resource>>
          matrix:
            parameters:
              tag: [jre8, jre11, jre17, jdk8, jdk11, jdk17]
              resource: [arm.medium, medium]
      - build-specific:
          name: forge-<<matrix.version>>-<<matrix.resource>>
          requires:
            - base-jre17-<<matrix.resource>>
          mc_type: Forge
          baseimage: jre17
          matrix:
            parameters:
              resource: [arm.medium, medium]
              version: [latest, '1.19.1', '1.19', '1.18.2', '1.17.1']

        
 
